package com.example.springcxf.client.endpoint.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-09T15:10:33.131+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://endpoint.server.springcxf.example.com/", name = "UserWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserWebService {

    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.server.springcxf.example.com/", className = "com.example.springcxf.client.endpoint.user.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.server.springcxf.example.com/", className = "com.example.springcxf.client.endpoint.user.CreateUserResponse")
    public void createUser(
        @WebParam(name = "createUserDTO", targetNamespace = "")
        com.example.springcxf.client.endpoint.user.CreateUserDTO createUserDTO
    );
}
